# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 54b352621071fb30395aa401a45bc8991b509c20fe294751b96b61197fc4042c33d4ed718cef3ad89f67f08cb5ae112cfc60b8e7996d7a4aac587cdfac6e1230

test:
  secret_key_base: e499b3a0c811b89a1933118313098a20467c0d4c55c77728296f96fd9d5b9301b50031d331c5bb5b5b8354722df1d3ad1d5b3fb23d881bec0123b6b655604325

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
